modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "jta"
version = "@version@"
displayName = "Jesse's Transit Addon"
authors = ["AwesomeKalin55", "Jesse"]
description = "Jesse's Transit Addon (JTA) is a collection of decorative and functional blocks for use with the MTR mod"
logoFile = "icon.png"

[[dependencies.jta]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jta]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"